# Generated by Django 5.2 on 2025-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
