# Generated by Django 5.2 on 2025-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicantprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('hanoi', 'Ha Noi'), ('hochiminh', 'Ho Chi Minh'), ('danang', 'Da Nang'), ('hue', 'Hue'), ('cantho', 'Can Tho'), ('others', 'Others')], max_length=20),
        ),
    ]
