# Generated by Django 5.2 on 2025-06-15 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_companyprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to='users.applicantprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Follower',
                'verbose_name_plural': 'Company Followers',
                'unique_together': {('applicant', 'company')},
            },
        ),
    ]
