# Generated by Django 5.2 on 2025-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companyfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
