# Generated by Django 5.2 on 2025-05-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystatistics',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='users.companyprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='users.companyprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.industry'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.applicantprofile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='cvreview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_review', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobstatistics',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.location'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='users.applicantprofile'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skilltag'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('applicant', 'job')},
        ),
    ]
