# Generated by Django 5.2 on 2025-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_location_address_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('fresher', 'Fresher'), ('junior', 'Junior (1-3 years)'), ('middle', 'Middle (3-5 years)'), ('senior', 'Senior (5+ years)'), ('lead', 'Lead'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=20),
        ),
    ]
