# Generated by Django 5.2 on 2025-05-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_experience_level_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, choices=[('hanoi', 'Ha Noi'), ('hochiminh', 'Ho Chi Minh'), ('danang', 'Da Nang'), ('hue', 'Hue'), ('cantho', 'Can Tho'), ('others', 'Others')], max_length=20),
        ),
    ]
