# Generated by Django 5.2 on 2025-06-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='application',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='CVReview',
        ),
        migrations.DeleteModel(
            name='InterviewSchedule',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
