# Generated by Django 5.2 on 2025-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_interviewschedule_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.TextField(blank=True),
        ),
    ]
