# Generated by Django 5.2 on 2025-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_preferred_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full time', 'Full time'), ('part time', 'Part time'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=20),
        ),
    ]
