# Generated by Django 5.2 on 2025-06-10 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_remove_interviewschedule_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProcessedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('industry', models.TextField(blank=True)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('basic_requirements', models.TextField(blank=True)),
                ('preferred_skills', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('combined_text', models.TextField(blank=True)),
                ('embedding_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='jobs.job')),
            ],
        ),
    ]
