# Generated by Django 5.2 on 2025-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_cvprocesseddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprocesseddata',
            name='achievements',
            field=models.TextField(blank=True),
        ),
    ]
