# Generated by Django 5.2 on 2025-06-12 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_cvprocesseddata_achievements'),
        ('application', '0001_initial'),
        ('jobs', '0007_job_preferred_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCVMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('detailed_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_match', to='application.jobapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_matches', to='jobs.job')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('job', 'application')},
            },
        ),
    ]
