# Generated by Django 5.2 on 2025-06-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_jobcvmatch'),
        ('application', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcvmatch',
            options={},
        ),
        migrations.RenameField(
            model_name='jobcvmatch',
            old_name='detailed_scores',
            new_name='detail_scores',
        ),
        migrations.AddField(
            model_name='cvprocesseddata',
            name='experience_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='jobcvmatch',
            name='cv_processed_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='AI.cvprocesseddata'),
        ),
        migrations.AddField(
            model_name='jobcvmatch',
            name='explanation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcvmatch',
            name='strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcvmatch',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobprocesseddata',
            name='experience_requirements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobcvmatch',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='application.jobapplication'),
        ),
    ]
