# Generated by Django 5.2 on 2025-06-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0005_alter_jobcvmatch_options_and_more'),
        ('AI', '0006_auto_20250625_0006'),
    ]

    operations = [
    ]
