# Generated by Django 5.2 on 2025-06-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0007_merge_20250625_0014"),
    ]

    operations = [
        # Không thực hiện thay đổi nào, chỉ đánh dấu là đã xử lý trường match_details
        migrations.RunSQL(
            "SELECT 1;",  # Không làm gì khi apply
            "SELECT 1;",  # Không làm gì khi rollback
        ),
    ]
