# Generated by Django 5.2 on 2025-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0008_auto_20250625_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcvmatch',
            name='match_details',
            field=models.JSONField(default=dict),
        ),
    ]
